
name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build oualidrahhouti/devops:1.0

      - name: Push docker image
        run: docker push oualidrahhouti/devops:1.0
  
      - name: Run Tests
        run: |
          npm install 
          npm test