
name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Pull docker image
        run: docker pull oualidrahhouti/devops

      - name: Run docker container
        run: docker run oualidrahhouti/devops
  
      - name: Run Tests
        run: |
          npm install 
          npm test